default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres

development:
  <<: *default
  database: covid_development

test:
  <<: *default
  database: covid_test

production:
  <<: *default
  database: covid_production
  username: covid
  password: <%= ENV['COVID_DATABASE_PASSWORD'] %>
